In [1]:
from transformers import pipeline
chatbot = pipeline(task="conversational",
                   model="facebook/blenderbot-400M-distill")

c:\App\Anaconda\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\App\Anaconda\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [2]:
user_message = """
What are some fun activities I can do in the summer?
"""

In [3]:
from transformers import Conversation
conversation = Conversation(user_message)
print(conversation)

Conversation id: f2cfdb21-464d-4e31-9a9b-8e4a49e14776
user: 
What are some fun activities I can do in the summer?




In [4]:
conversation = chatbot(conversation)
print(conversation)


No chat template is defined for this tokenizer - using the default template for the BlenderbotTokenizerFast class. If the default is not appropriate for your model, please set `tokenizer.chat_template` to an appropriate template. See https://huggingface.co/docs/transformers/main/chat_templating for more information.



Conversation id: f2cfdb21-464d-4e31-9a9b-8e4a49e14776
user: 
What are some fun activities I can do in the summer?

assistant:  I love going to the beach and swimming in the ocean. What about you?



In [5]:
conversation.add_message(
    {"role": "user",
     "content": """
What else do you recommend?
"""
    })
print(conversation)

Conversation id: f2cfdb21-464d-4e31-9a9b-8e4a49e14776
user: 
What are some fun activities I can do in the summer?

assistant:  I love going to the beach and swimming in the ocean. What about you?
user: 
What else do you recommend?




In [6]:
conversation = chatbot(conversation)
print(conversation)

Conversation id: f2cfdb21-464d-4e31-9a9b-8e4a49e14776
user: 
What are some fun activities I can do in the summer?

assistant:  I love going to the beach and swimming in the ocean. What about you?
user: 
What else do you recommend?

assistant:  I also like to go to the lake and swim in the river. 



In [7]:
conversation.add_message(
    {"role": "user",
     "content": """
Suggest more activities for the summer.
"""
    })

In [8]:
conversation = chatbot(conversation)
print(conversation)

Conversation id: f2cfdb21-464d-4e31-9a9b-8e4a49e14776
user: 
What are some fun activities I can do in the summer?

assistant:  I love going to the beach and swimming in the ocean. What about you?
user: 
What else do you recommend?

assistant:  I also like to go to the lake and swim in the river. 
user: 
Suggest more activities for the summer.

assistant:  I like to hike in the mountains and camping in the woods. 



In [9]:
# Translation
from transformers.utils import logging
logging.set_verbosity_error()
from transformers import pipeline 
import torch


translator = pipeline(task="translation",
                      model="facebook/nllb-200-distilled-600M",
                      torch_dtype=torch.bfloat16) 

In [40]:
text = """\
My puppy is adorable, \
Your kitten is cute.
Her panda is friendly.
His llama is thoughtful. \
We all have nice pets!"""

In [45]:
text_translated = translator(text,
                             src_lang="eng_Latn",
                             tgt_lang="fra_Latn")
text_translated

[{'translation_text': 'Mon chiot est adorable, ton chaton est mignon, son panda est ami, sa lamme est attentive, nous avons tous de beaux animaux de compagnie.'}]

In [10]:
# Free memory
import gc
del translator
gc.collect()

79

In [11]:
summarizer = pipeline(task="summarization",
                      model="facebook/bart-large-cnn",
                      torch_dtype=torch.bfloat16)

In [73]:
text = """Paris is the capital and most populous city of France, with
          an estimated population of 2,175,601 residents as of 2018,
          in an area of more than 105 square kilometres (41 square
          miles). The City of Paris is the centre and seat of
          government of the region and province of Île-de-France, or
          Paris Region, which has an estimated population of
          12,174,880, or about 18 percent of the population of France
          as of 2017."""         

In [74]:
summary = summarizer(text,
                     min_length=10,
                     max_length=200) 
summary

[{'summary_text': 'Paris is the capital and most populous city of France, with an estimated population of 2,175,601 residents as of 2018. The City of Paris is the centre and seat of the government of the region and province of Île-de-France.'}]

In [75]:
from sentence_transformers import SentenceTransformer


model = SentenceTransformer("all-MiniLM-L6-v2")

In [76]:
sentences1 = ['The cat sits outside',
              'A man is playing guitar',
              'The movies are awesome']

embeddings1 = model.encode(sentences1, convert_to_tensor=True)

print(embeddings1)

sentences2 = ['The dog plays in the garden',
              'A woman watches TV',
              'The new movie is so great']

embeddings2 = model.encode(sentences2, 
                           convert_to_tensor=True)

print(embeddings2)

tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])
tensor([[ 0.0163, -0.0700,  0.0384,  ...,  0.0447,  0.0254, -0.0023],
        [ 0.0054, -0.0920,  0.0140,  ...,  0.0167, -0.0086, -0.0424],
        [-0.0842, -0.0592, -0.0010,  ..., -0.0157,  0.0764,  0.0389]])


In [77]:
from sentence_transformers import util

cosine_scores = util.cos_sim(embeddings1,embeddings2)
print(cosine_scores)

tensor([[ 0.2838,  0.1310, -0.0029],
        [ 0.2277, -0.0327, -0.0136],
        [-0.0124, -0.0465,  0.6571]])


In [78]:
for i in range(len(sentences1)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i],
                                                 sentences2[i],
                                                 cosine_scores[i][i]))

The cat sits outside 		 The dog plays in the garden 		 Score: 0.2838
A man is playing guitar 		 A woman watches TV 		 Score: -0.0327
The movies are awesome 		 The new movie is so great 		 Score: 0.6571
