In [ ]:
from transformers import pipeline
chatbot = pipeline(task="conversational",
                   model="facebook/blenderbot-400M-distill")

In [31]:
user_message = """
What are some fun activities I can do in the summer?
"""

In [32]:
from transformers import Conversation
conversation = Conversation(user_message)
print(conversation)

Conversation id: bf39d7ea-c994-4476-b08c-aba1931f9c43
user: 
What are some fun activities I can do in the summer?




In [33]:
conversation = chatbot(conversation)
print(conversation)

Conversation id: bf39d7ea-c994-4476-b08c-aba1931f9c43
user: 
What are some fun activities I can do in the summer?

assistant:  I love going to the beach and swimming in the ocean. What about you?



In [34]:
conversation.add_message(
    {"role": "user",
     "content": """
What else do you recommend?
"""
    })
print(conversation)

Conversation id: bf39d7ea-c994-4476-b08c-aba1931f9c43
user: 
What are some fun activities I can do in the summer?

assistant:  I love going to the beach and swimming in the ocean. What about you?
user: 
What else do you recommend?




In [35]:
conversation = chatbot(conversation)
print(conversation)

Conversation id: bf39d7ea-c994-4476-b08c-aba1931f9c43
user: 
What are some fun activities I can do in the summer?

assistant:  I love going to the beach and swimming in the ocean. What about you?
user: 
What else do you recommend?

assistant:  I also like to go to the lake and swim in the river. 



In [36]:
conversation.add_message(
    {"role": "user",
     "content": """
Suggest more activities for the summer.
"""
    })

In [38]:
conversation = chatbot(conversation)
print(conversation)

Conversation id: bf39d7ea-c994-4476-b08c-aba1931f9c43
user: 
What are some fun activities I can do in the summer?

assistant:  I love going to the beach and swimming in the ocean. What about you?
user: 
What else do you recommend?

assistant:  I also like to go to the lake and swim in the river. 
user: 
Suggest more activities for the summer.

assistant:  I like to hike in the mountains and camping in the woods. 



In [39]:
# Translation
from transformers.utils import logging
logging.set_verbosity_error()
from transformers import pipeline 
import torch


translator = pipeline(task="translation",
                      model="facebook/nllb-200-distilled-600M",
                      torch_dtype=torch.bfloat16) 

In [40]:
text = """\
My puppy is adorable, \
Your kitten is cute.
Her panda is friendly.
His llama is thoughtful. \
We all have nice pets!"""

In [43]:
jabberwocky_text = """Jabberwocky
von Lewis Carroll
Twas brillig, and the slithy toves
Did gyre and gimble in the wabe;
All mimsy were the borogoves,
And the mome raths outgrabe.

Beware the Jabberwock, my son!
The jaws that bite, the claws that catch!
Beware the Jubjub bird, and shun
The frumious Bandersnatch!

He took his vorpal sword in hand:
Long time the manxome foe he sought
So rested he by the Tumtum tree,
And stood awhile in thought.

And as in uffish thought he stood,
The Jabberwock, with eyes of flame,
Came whiffling through the tulgey wood,
And burbled as it came!

One, two! One, two! And through and through
The vorpal blade went snicker-snack!
He left it dead, and with its head
He went galumphing back.

And hast thou slain the Jabberwock?
Come to my arms, my beamish boy!
O frabjous day! Callooh! Callay!
He chortled in his joy.

Twas brillig, and the slithy toves
Did gyre and gimble in the wabe;
All mimsy were the borogoves,
And the mome raths outgrabe."""

In [45]:
text_translated = translator(text,
                             src_lang="eng_Latn",
                             tgt_lang="fra_Latn")
text_translated

[{'translation_text': 'Mon chiot est adorable, ton chaton est mignon, son panda est ami, sa lamme est attentive, nous avons tous de beaux animaux de compagnie.'}]

In [46]:
text_translated = translator(jabberwocky_text,
                             src_lang="eng_Latn",
                             tgt_lang="fra_Latn")
text_translated

[{'translation_text': "Jabberwocky von Lewis Carroll était brillant, et les toves glissantes tournaient et gémissaient dans le wabe; tous les mimes étaient les borogoves, et les mames s'étaient écrasés. Prenez garde au Jabberwock, mon fils! Les mâchoires qui mordent, les griffes qui attraperent! Prenez garde à l'oiseau Jubjub, et évitez le flagrant Bandersnatch! Il prit son épée vorpère dans la main: longtemps l'ennemi manxome qu'il cherchait Il se reposa donc près de l'arbre Tumtum, et se tint un moment en pensée. Et comme dans l'ufish il pensait qu'il se tenait, le Jabberwock, avec des yeux de flamme, vint souffler à travers le bois, et se roulait comme il"}]

In [47]:
# Free memory
import gc
del translator
gc.collect()

1025

In [ ]:
summarizer = pipeline(task="summarization",
                      model="facebook/bart-large-cnn",
                      torch_dtype=torch.bfloat16)

In [73]:
text = """Paris is the capital and most populous city of France, with
          an estimated population of 2,175,601 residents as of 2018,
          in an area of more than 105 square kilometres (41 square
          miles). The City of Paris is the centre and seat of
          government of the region and province of Île-de-France, or
          Paris Region, which has an estimated population of
          12,174,880, or about 18 percent of the population of France
          as of 2017."""         

In [74]:
summary = summarizer(text,
                     min_length=10,
                     max_length=200) 
summary

[{'summary_text': 'Paris is the capital and most populous city of France, with an estimated population of 2,175,601 residents as of 2018. The City of Paris is the centre and seat of the government of the region and province of Île-de-France.'}]

In [75]:
from sentence_transformers import SentenceTransformer


model = SentenceTransformer("all-MiniLM-L6-v2")

In [76]:
sentences1 = ['The cat sits outside',
              'A man is playing guitar',
              'The movies are awesome']

embeddings1 = model.encode(sentences1, convert_to_tensor=True)

print(embeddings1)

sentences2 = ['The dog plays in the garden',
              'A woman watches TV',
              'The new movie is so great']

embeddings2 = model.encode(sentences2, 
                           convert_to_tensor=True)

print(embeddings2)

tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])
tensor([[ 0.0163, -0.0700,  0.0384,  ...,  0.0447,  0.0254, -0.0023],
        [ 0.0054, -0.0920,  0.0140,  ...,  0.0167, -0.0086, -0.0424],
        [-0.0842, -0.0592, -0.0010,  ..., -0.0157,  0.0764,  0.0389]])


In [77]:
from sentence_transformers import util

cosine_scores = util.cos_sim(embeddings1,embeddings2)
print(cosine_scores)

tensor([[ 0.2838,  0.1310, -0.0029],
        [ 0.2277, -0.0327, -0.0136],
        [-0.0124, -0.0465,  0.6571]])


In [78]:
for i in range(len(sentences1)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i],
                                                 sentences2[i],
                                                 cosine_scores[i][i]))

The cat sits outside 		 The dog plays in the garden 		 Score: 0.2838
A man is playing guitar 		 A woman watches TV 		 Score: -0.0327
The movies are awesome 		 The new movie is so great 		 Score: 0.6571
